#!/usr/bin/env python

from string import Template
import argparse
import sys


def main(argv):
    parser = argparse.ArgumentParser(description='Substitute strings')
    parser.add_argument('-c', metavar='config',
            help='read variables from config file')
    parser.add_argument('-d', nargs=2, metavar=('name', 'value'),
            action='append', help='define variable')
    parser.add_argument('-o', metavar='output', required=True,
            help='output file')
    parser.add_argument('-t', metavar='template', required=True,
            help='template file')
    args = parser.parse_args()

    with open(args.t, 'r') as template_file:
        template_string = template_file.read()
    template = Template(template_string)

    mapping = {}
    if args.d:
        mapping.update(args.d)
    if args.c:
        with open(args.c, 'r') as config_file:
            mapping.update(config_line.split('=', 1)
                           for config_line in config_file.xreadlines())

    output = template.substitute(mapping)

    with open(args.o, 'w') as output_file:
        output_file.write(output)

    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
